# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_docs_without_aggregate_type_defaults
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_tflint
        args:
          - --args=--recursive
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 33.2.2
    hooks:
      - id: renovate-config-validator
