name: Validate and Plan Terraform

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
 run:
  shell: bash

env:
  TERRAFORM_VERSION: 1.5.7
  TFLINT_VERSION: 0.50.1

permissions:
  id-token: write
  contents: read
  security-events: write
  pull-requests: read

jobs:
  lint-validate-and-plan:
    name: 'Validate Infrastructure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0
        name: Setup TFLint
        with:
          tflint_version: v${{ env.TFLINT_VERSION }}

      - name: Check Formating
        id: tf_fmt
        run: terraform fmt -check -recursive

      - name: Lint Terraform
        id: tf_lint
        run: tflint --recursive

      - name: Configure OIDC AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::311462405659:role/aws-cost-notifier-oidc-role
          role-session-name: opg-aws-cost-notifier-github-actions-pull
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7
        with:
          registries: 311462405659

      - name: Snky IAC
        id: snyk_iac
        uses: ministryofjustice/opg-github-actions/actions/snyk-iac@722a5f955424aaba01e9ca43d68390cd4048d6e1 # v4.10.2
        with:
          iac_test_directory: "./"
          sarif_filename: "snyk-iac.sarif"
          SNYK_TOKEN: ${{ secrets.snyk_opg_org_token }}
          snyk_test_args: "--exclude=local"

      - name: Upload Snyk IAC scan results to GitHub Security tab
        id: snyk_upload_sarif
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        if: always()
        with:
          category: "Terraform"
          sarif_file: "test-results/snyk-iac.sarif"

      - name: Validate & Plan Terraform
        id: tf_validate
        run: make terraform
